"Filed out from Dolphin Smalltalk"!

WADecoration subclass: #UpDecoration
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

UpDecoration guid: (GUID fromString: '{6b5ad8a2-e779-44b7-b571-adddff4798e3}')!

UpDecoration comment: ''!

!UpDecoration categoriesForClass!Base! !

!UpDecoration methodsFor!

rendererClass

	^UpHtmlCanvas! !

!UpDecoration categoriesForMethods!
rendererClass!public!rendering! !
!

